name: Github Pages
on:
    push:
        branches:
            - dev
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [v16.18.1]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install && Build
              run: |
                  npm install
                  npm run build

            - name: GrayEnv
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.GRAY_HOST }}
                  username: ${{ secrets.GRAY_HOST_USERNAME }}
                  key: ${{ secrets.GRAY_HOST_PRIVATEKEY }}
                  source: dist/*
                  target: /www/wwwroot/jx3box/test

